FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake pandoc yasm

ADD . /repo
WORKDIR /repo/build
RUN cmake .. -DPTDUMP=1
RUN make -j8
